USE [master]
GO
/****** Object:  Database [UMVELTEST]    Script Date: 7/2/2023 10:49:38 AM ******/
CREATE DATABASE [UMVELTEST]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UMVELTEST', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UMVELTEST.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UMVELTEST_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UMVELTEST_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [UMVELTEST] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UMVELTEST].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UMVELTEST] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UMVELTEST] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UMVELTEST] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UMVELTEST] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UMVELTEST] SET ARITHABORT OFF 
GO
ALTER DATABASE [UMVELTEST] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UMVELTEST] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UMVELTEST] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UMVELTEST] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UMVELTEST] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UMVELTEST] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UMVELTEST] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UMVELTEST] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UMVELTEST] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UMVELTEST] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UMVELTEST] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UMVELTEST] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UMVELTEST] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UMVELTEST] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UMVELTEST] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UMVELTEST] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UMVELTEST] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UMVELTEST] SET RECOVERY FULL 
GO
ALTER DATABASE [UMVELTEST] SET  MULTI_USER 
GO
ALTER DATABASE [UMVELTEST] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UMVELTEST] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UMVELTEST] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UMVELTEST] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UMVELTEST] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UMVELTEST] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'UMVELTEST', N'ON'
GO
ALTER DATABASE [UMVELTEST] SET QUERY_STORE = OFF
GO
USE [UMVELTEST]
GO
/****** Object:  Table [dbo].[Concept]    Script Date: 7/2/2023 10:49:39 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Concept](
	[ConceptId] [int] IDENTITY(1,1) NOT NULL,
	[Quantity] [decimal](18, 0) NOT NULL,
	[ProductId] [int] NOT NULL,
	[SaleId] [int] NOT NULL,
	[UnitPrice] [decimal](18, 0) NOT NULL,
	[Amount] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_Concept] PRIMARY KEY CLUSTERED 
(
	[ConceptId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 7/2/2023 10:49:39 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CustomerId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 7/2/2023 10:49:39 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[UnitPrice] [varchar](50) NOT NULL,
	[Cost] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sale]    Script Date: 7/2/2023 10:49:39 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sale](
	[SaleId] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[Total] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_Sale] PRIMARY KEY CLUSTERED 
(
	[SaleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Concept]  WITH CHECK ADD  CONSTRAINT [FK_Concept_Product] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([ProductId])
GO
ALTER TABLE [dbo].[Concept] CHECK CONSTRAINT [FK_Concept_Product]
GO
ALTER TABLE [dbo].[Concept]  WITH CHECK ADD  CONSTRAINT [FK_Concept_Sale] FOREIGN KEY([SaleId])
REFERENCES [dbo].[Sale] ([SaleId])
GO
ALTER TABLE [dbo].[Concept] CHECK CONSTRAINT [FK_Concept_Sale]
GO
ALTER TABLE [dbo].[Sale]  WITH CHECK ADD  CONSTRAINT [FK_Sale_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([CustomerId])
GO
ALTER TABLE [dbo].[Sale] CHECK CONSTRAINT [FK_Sale_Customer]
GO
USE [master]
GO
ALTER DATABASE [UMVELTEST] SET  READ_WRITE 
GO
